name: humanmotion
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow-cpu
      - mediapipe
      - opencv-python
      - pandas
      - numpy
      - scikit-learn
